build:
  version: "1.0"

accounts:
  message: "Hey, welcome to EazyBank accounts related webhook APIs"
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "{cipher}65a2b9837987c7a5b683ec5996deadaf8cc3a8010363821348c81cc744bf3497bcf77c37e13d69c1e1e85f63dc064a52"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
